### ISSUE TITLE
chrome install

### ISSUE THREAD

**Issue by nchudleigh** [matthewbstokes-zz/freshbuntu#2]
Google Chrome isn't in the repositories - chromium is though

To install Google Chrome, run the following:

sudo apt-get install libxss1
wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb  
//in the above command change i386 to amd64 if you are running an amd cpu
sudo dpkg -i google-chrome*.deb

This will install the actual google chrome

**Comment by matthewbstokes-zz** [comment]
fixed in the install script it even checks for which architecture you have and installs the appropriate package.
